services:
    nestjs:
        image: johannesschaefer/nestjs:${TAG:-dev}
        build:
            context: .
            dockerfile: ./dockerfiles/nestjs/Dockerfile
            target: dev
            args:
                - NODE_ENV=development
        command: npm run start:debug
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        container_name: nestjs
        ports:
            - 127.0.0.1:3000:3000
            - 127.0.0.1:9229:9229
        env_file:
            - .env
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - app-network

    mongodb:
        image: johannesschaefer/mongo:${TAG:-dev}
        build:
            context: .
            dockerfile: ./dockerfiles/mongodb/Dockerfile
        container_name: mongodb
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
        volumes:
            - mongodb_data:/data/db/
            - mongodb_log:/var/log/mongodb/
            - ./mongo:/docker-entrypoint-initdb.d:ro
        ports:
            - '127.0.0.1:27017:27017'
        networks:
            - app-network

volumes:
    mongodb_data:
    mongodb_log:

networks:
    app-network:
        driver: bridge
