services:
    nestjs:
        image: johannesschaefer/nestjs:prod
        command: npm run start:prod
        container_name: nestjs
        env_file:
            - .env.prod
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - app-network

    mongodb:
        image: johannesschaefer/mongo:prod
        container_name: mongodb
        env_file:
            - .env.prod
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
        volumes:
            - mongodb_data:/data/db/
            - mongodb_log:/var/log/mongodb/
            - ./mongo:/docker-entrypoint-initdb.d:ro
        networks:
            - app-network
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    nginx:
        image: johannesschaefer/nginx:prod
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /etc/ssl/certs/cloudflare-origin-fullchain.pem:/etc/ssl/certs/cloudflare-origin-fullchain.pem:ro
            - /etc/ssl/private/cloudflare-origin.key:/etc/ssl/private/cloudflare-origin.key:ro
        networks:
            - app-network
        depends_on:
            - nestjs

    mongodb-exporter:
        image: percona/mongodb_exporter:0.47.1
        container_name: mongodb-exporter
        environment:
            - MONGODB_URI=mongodb://${MONGO_DB_METRICS_USERNAME}:${MONGO_DB_METRICS_PASSWORD}@${MONGO_DB_HOSTNAME}:${MONGO_DB_PORT}/${MONGO_DB_DATABASE}?authSource=admin
        ports:
            - '9216:9216'
        depends_on:
            - mongodb
        networks:
            - app-network

volumes:
    mongodb_data:
    mongodb_log:

networks:
    app-network:
        driver: bridge
