services:
    nestjs:
        image: nestjs:latest
        build:
            context: .
            target: builder
            dockerfile: Dockerfile
            tags:
                - johannesschaefer/nestjs:latest
        container_name: nestjs
        ports:
            - 3000:3000
            - 9229:9229
        command: npm run start:debug
        env_file:
            - .env
        depends_on:
            - mongodb
        restart: always
        networks:
            - app-network

    mongodb:
        image: mongo:latest
        build:
            tags:
                - johannesschaefer/mongo:latest
        container_name: mongodb
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} # only for auth against admin database
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} # only for auth against admin database
            - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE} # the databse that will run the init scripts
        volumes:
            - mongodb_data:/data/db/
            - mongodb_log:/var/log/mongodb/
            - ./mongo/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
        ports:
            - '27017:27017'
        restart: always
        healthcheck:
            test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app-network

    nginx:
        image: nginx:latest
        build:
            tags:
                - johannesschaefer/nginx:latest
        ports:
            - '443:443'
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nestjs
        restart: always
        env_file:
            - .env
        networks:
            - app-network
    cloudflare-ddns:
        image: oznu/cloudflare-ddns:latest
        build:
            tags:
                - johannesschaefer/cloudflare-ddns:latest
        restart: always
        environment:
            - API_KEY=${CLOUDFLARE_APIKEY}
            - ZONE=schaeferdevelopment.tech
            - PROXIED=true
            - PUID=1000
            - PGID=1000
        networks:
            - app-network
volumes:
    mongodb_data:
        driver: local
        name: mongodb-data

    mongodb_log:
        driver: local
        name: mongodb-log

networks:
    app-network:
        driver: bridge
        attachable: true
        name: app-network
