services:
    nestjs:
        ports:
            - '3000:3000'
            - '9229:9229' # Debug port
        container_name: nestjs-local

    mongodb:
        container_name: mongodb-local

    nginx:
        ports:
            - '80:80'
        container_name: nginx-local

    mongodb-exporter:
        container_name: mongodb-exporter-local
