services:
    app:
        image: johannesschaefer/nestjs-api
        build:
            context: .
            dockerfile: Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
        env_file:
            - .env
        depends_on:
            - mongo
        restart: always

    mongo:
        image: mongo:latest
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
        volumes:
            - mongodb_data:/data/db/
            - mongodb_log:/var/log/mongodb/
        ports:
            - '27017:27017'
        restart: always
        healthcheck:
            test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: johannesschaefer/nginx
        build:
            context: .
            x-bake:
                platforms:
                    - linux/amd64
        ports:
            - '443:443'
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        restart: always
        env_file:
            - .env
    cloudflare-ddns:
        image: oznu/cloudflare-ddns:latest
        restart: always
        environment:
            - API_KEY=W0qI1iFbmD1bx-n_nN0v00oVMmgW0tMayZONfRqD
            - ZONE=schaeferdevelopment.tech
            - PROXIED=true
            - PUID=1000
            - PGID=1000

volumes:
    mongodb_data:
        driver: local
        name: mongodb-data
    mongodb_log:
        driver: local
        name: mongodb-log

networks:
    app-network:
        driver: bridge
