services:
    app:
        image: nestjs-api
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/arm/v7

        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
        env_file:
            - .env
        depends_on:
            - mongo
        restart: always
    mongo:
        image: mongo:latest
        platform: linux/arm/v7
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
        volumes:
            - mongodb_data:/data/db/
            - mongodb-log:/var/log/mongodb/
        ports:
            - '27017:27017'
        restart: always
    nginx:
        image: nginx:latest
        platform: linux/arm/v7
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        links:
            - app
        restart: always

volumes:
    mongodb_data:
        driver: local
        name: mongo-data
    mongodb-log:
        driver: local
        name: mongo-log
