services:
    nestjs:
        image: johannesschaefer/nestjs:prod
        command: npm run start:prod

    mongodb:
        image: johannesschaefer/mongodb:prod

    nginx:
        image: johannesschaefer/nginx:prod
        volumes:
            - /etc/ssl/certs:/etc/ssl/certs:ro
            - /etc/ssl/private:/etc/ssl/private:ro
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - nestjs
    mongodb-exporter:
        image: percona/mongodb_exporter:0.47.1
        container_name: mongodb-exporter
        env_file:
            - .env.prod
        environment:
            - MONGODB_HOST=${MONGO_DB_HOSTNAME}
            - MONGODB_PORT=${MONGO_DB_PORT}
            - MONGODB_USERNAME=${MONGO_DB_METRICS_USERNAME}
            - MONGODB_PASSWORD=${MONGO_DB_METRICS_PASSWORD}
            - MONGODB_DATABASE=${MONGO_DB_DATABASE}
            - MONGODB_AUTH_SOURCE=admin
        ports:
            - '9216:9216'
        depends_on:
            - mongodb
        networks:
            - app-network
