name: Build and Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images for dev
      run: |
        export TAG=dev
        export CLOUDFLARE_APIKEY=${{ secrets.CLOUDFLARE_APIKEY }}
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml push
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        export TAG=latest
        export CLOUDFLARE_APIKEY=${{ secrets.CLOUDFLARE_APIKEY }}
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml push
