name: Deploy

on:
    push:
        branches:
            - main
            - dev

jobs:
    build-dev:
        if: github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Override env variables
              run: |
                  echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
                  echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
                  echo "MONGO_DB_DATABASE=${{ secrets.MONGO_DB_DATABASE }}" >> .env
                  echo "API_KEY=${{ secrets.CLOUDFLARE_APIKEY }}" >> .env

            - name: Build and push Docker images for dev
              env:
                  CLOUDFLARE_APIKEY: ${{ secrets.CLOUDFLARE_APIKEY }}
                  TAG: dev
              run: |
                  docker compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
                  docker compose -f docker-compose.yml -f docker-compose.dev.yml push

    build-main:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Override env variables
              run: |
                  echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
                  echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
                  echo "MONGO_DB_DATABASE=${{ secrets.MONGO_DB_DATABASE }}" >> .env
                  echo "API_KEY=${{ secrets.CLOUDFLARE_APIKEY }}" >> .env

            - name: Build and push Docker images for main
              env:
                  CLOUDFLARE_APIKEY: ${{ secrets.CLOUDFLARE_APIKEY }}
                  TAG: prod
              run: |
                  docker compose -f docker-compose.yml -f docker-compose.prod.yml build --no-cache
                  docker compose -f docker-compose.yml -f docker-compose.prod.yml push
